//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://Dsi.Tools.Common.servicehost.wcf/test", ConfigurationName="IStatusQuerable")]
public interface IStatusQuerable
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Dsi.Tools.Common.servicehost.wcf/test/IStatusQuerable/QueryForStatus", ReplyAction="http://Dsi.Tools.Common.servicehost.wcf/test/IStatusQuerable/QueryForStatusResponse")]
    string QueryForStatus();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IStatusQuerableChannel : IStatusQuerable, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class StatusQuerableClient : System.ServiceModel.ClientBase<IStatusQuerable>, IStatusQuerable
{
    
    public StatusQuerableClient()
    {
    }
    
    public StatusQuerableClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public StatusQuerableClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StatusQuerableClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StatusQuerableClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string QueryForStatus()
    {
        return base.Channel.QueryForStatus();
    }
}
