//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Tools.Commands.Implementation.IF1.Tao
{
    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.3038.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.tibco.com/schemas/SDPRO_Observer/Observer/SharedResources/XSD/IF1/Term" +
        "inateAddonMP.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.tibco.com/schemas/SDPRO_Observer/Observer/SharedResources/XSD/IF1/Term" +
        "inateAddonMP.xsd", IsNullable = false)]
    public partial class TerminateAddonMP
    {

        private req reqField;

        private res resField;

        /// <remarks/>
        public req req
        {
            get
            {
                return this.reqField;
            }
            set
            {
                this.reqField = value;
            }
        }

        /// <remarks/>
        public res res
        {
            get
            {
                return this.resField;
            }
            set
            {
                this.resField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.tibco.com/schemas/SDPRO_Observer/Observer/SharedResources/XSD/IF1/Term" +
        "inateAddonMP.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.tibco.com/schemas/SDPRO_Observer/Observer/SharedResources/XSD/IF1/Term" +
        "inateAddonMP.xsd", IsNullable = false)]
    public partial class req
    {

        private cid cidField;

        private string tISwalletIdField;

        private MP mpField;

        private string phoneNumberField;

        private string reqIdField;

        private System.DateTime reqTimeField;

        /// <remarks/>
        public cid cid
        {
            get
            {
                return this.cidField;
            }
            set
            {
                this.cidField = value;
            }
        }

        /// <remarks/>
        public string TISwalletId
        {
            get
            {
                return this.tISwalletIdField;
            }
            set
            {
                this.tISwalletIdField = value;
            }
        }

        /// <remarks/>
        public MP MP
        {
            get
            {
                return this.mpField;
            }
            set
            {
                this.mpField = value;
            }
        }

        /// <remarks/>
        public string phoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }

        /// <remarks/>
        public string reqId
        {
            get
            {
                return this.reqIdField;
            }
            set
            {
                this.reqIdField = value;
            }
        }

        /// <remarks/>
        public System.DateTime reqTime
        {
            get
            {
                return this.reqTimeField;
            }
            set
            {
                this.reqTimeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.tibco.com/schemas/SDPRO_Observer/Observer/SharedResources/XSD/IF1/AllT" +
        "ypes.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.tibco.com/schemas/SDPRO_Observer/Observer/SharedResources/XSD/IF1/Term" +
        "inateAddonMP.xsd", IsNullable = false)]
    public partial class cid
    {

        private string itemField;

        private ItemChoiceType itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TISTDid", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("TIScustomerId", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.tibco.com/schemas/SDPRO_Observer/Observer/SharedResources/XSD/IF1/AllT" +
        "ypes.xsd", IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        TISTDid,

        /// <remarks/>
        TIScustomerId,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.tibco.com/schemas/SDPRO_Observer/Observer/SharedResources/XSD/IF1/Term" +
        "inateAddonMP.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.tibco.com/schemas/SDPRO_Observer/Observer/SharedResources/XSD/IF1/Term" +
        "inateAddonMP.xsd", IsNullable = false)]
    public partial class MP
    {

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "positiveInteger")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.tibco.com/schemas/SDPRO_Observer/Observer/SharedResources/XSD/IF1/Term" +
        "inateAddonMP.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.tibco.com/schemas/SDPRO_Observer/Observer/SharedResources/XSD/IF1/Term" +
        "inateAddonMP.xsd", IsNullable = false)]
    public partial class res
    {

        private result resultField;

        /// <remarks/>
        public result result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.tibco.com/schemas/SDPRO_Observer/Observer/SharedResources/XSD/IF1/AllT" +
        "ypes.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.tibco.com/schemas/SDPRO_Observer/Observer/SharedResources/XSD/IF1/Term" +
        "inateAddonMP.xsd", IsNullable = false)]
    public partial class result
    {

        private string codeField;

        private string descField;

        /// <remarks/>
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string desc
        {
            get
            {
                return this.descField;
            }
            set
            {
                this.descField = value;
            }
        }
    }
}