//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tools.Tracing.UI {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class ApplicationEventsGuiSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ApplicationEventsGuiSettings defaultInstance = ((ApplicationEventsGuiSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ApplicationEventsGuiSettings())));
        
        public static ApplicationEventsGuiSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XQueryLibraryPath {
            get {
                return ((string)(this["XQueryLibraryPath"]));
            }
            set {
                this["XQueryLibraryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XPathLibraryPath {
            get {
                return ((string)(this["XPathLibraryPath"]));
            }
            set {
                this["XPathLibraryPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("944, 416")]
        public global::System.Drawing.Size MainFormSize {
            get {
                return ((global::System.Drawing.Size)(this["MainFormSize"]));
            }
            set {
                this["MainFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool showTestToolBarMenuItemChecked {
            get {
                return ((bool)(this["showTestToolBarMenuItemChecked"]));
            }
            set {
                this["showTestToolBarMenuItemChecked"] = value;
            }
        }
    }
}
