//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Tools.Commands.Implementation.IF1 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tibco.com/schemas/SDPRO_Observer/Observer/SharedResources/XSD/IF1/Upda" +
        "teProcessing.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.tibco.com/schemas/SDPRO_Observer/Observer/SharedResources/XSD/IF1/Upda" +
        "teProcessing.xsd", IsNullable=false)]
    public partial class UpdateProcessing {
        
        private req reqField;
        
        private string resField;
        
        /// <remarks/>
        public req req {
            get {
                return this.reqField;
            }
            set {
                this.reqField = value;
            }
        }
        
        /// <remarks/>
        public string res {
            get {
                return this.resField;
            }
            set {
                this.resField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.tibco.com/schemas/SDPRO_Observer/Observer/SharedResources/XSD/IF1/Upda" +
        "teProcessing.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.tibco.com/schemas/SDPRO_Observer/Observer/SharedResources/XSD/IF1/Upda" +
        "teProcessing.xsd", IsNullable=false)]
    public partial class req {
        
        private string reqIdField;
        
        private string processingStatusField;
        
        private string updateMechanismField;
        
        private string errorDescField;
        
        private string returnValueField;
        
        /// <remarks/>
        public string reqId {
            get {
                return this.reqIdField;
            }
            set {
                this.reqIdField = value;
            }
        }
        
        /// <remarks/>
        public string processingStatus {
            get {
                return this.processingStatusField;
            }
            set {
                this.processingStatusField = value;
            }
        }
        
        /// <remarks/>
        public string updateMechanism {
            get {
                return this.updateMechanismField;
            }
            set {
                this.updateMechanismField = value;
            }
        }
        
        /// <remarks/>
        public string errorDesc {
            get {
                return this.errorDescField;
            }
            set {
                this.errorDescField = value;
            }
        }
        
        /// <remarks/>
        public string returnValue {
            get {
                return this.returnValueField;
            }
            set {
                this.returnValueField = value;
            }
        }
    }
}
