namespace Tools.Coordination.ProducerConsumer
{
    public enum JobConsumerMessage
    {
        ReadingParameterFromConfiguration = 2601,
        ObtainedMessageFromRetrievedItems = 2602,
        CallingMonitorWaitOnSubmittedItems = 2603,
        ItemAddedToSubmittedItems = 2604,
        DelayedMessageArrived = 2605,
        DelayingMessageRetrieval = 2606,
        ParametersUpdateFailed = 2651,
        StopRequestedAfterSubmissionToSender = 2607,
        ErrorResponseNotificationCreated = 2608,
        AbortRequested = 2608,
        ThreadInterrupted = 2609,
        RequestingNewMessageToBeRead = 2202,
        SubmittingMessageToTheSender = 2203,
        ResponseReceivedFromTheSender = 2204,
        SkippingExternallyResolvedPendingResubmission = 2205,
        SubmittingMessageToTheSenderWillBeSkipped = 2206,
        WorkItemFullyProcessed = 2208,
        InvalidResultType = 2251,
        MissingOrInvalidParameter = 2253,
        InvalidMessageType = 2254,
        SendingMessageToSubmittedItemsFailed = 2255,
        SendingMessageToSubmittedQueueFailed = 2256,
        RemovingMessageFromSubmittedItemsFailed = 2257,
        ProcessingMessageFailed = 2258,
        SendingMessageToAfterResponseObtainedQueue = 2259,
        RemovingMessageFromSubmittedQueueFailed = 2260,
        QueueWorkItemsConsumerStarted = 2261,
        ErrorObtainingQueueWorkItem = 2262,
        SendingMessageToFailedQueueFailed = 2263,
        RequestSavedInFailedQueue = 2264,
        SendingMessageToMSMQFailed = 2265,
        MessageRetrievalFromSubmittedItemsFailed = 2266,
        IncorrectMessageType = 2267,
        IncorrectMessageFormat = 2268,
        ErrorInSenderAsyncCall = 2270,
        InvalidItemType = 2271,
        SendingMessageToTheSenderTimedOut = 2272,
        FailureCausedStoppingConsumerProcessing = 2273,
        UnexpectedSubmissionStatus = 2274,
        ErrorOccuredInConsumerLoop = 2275,
        PreHandleNotSuccessful = 2276,
        ErrorOccuredInConsumer = 2277,
        ErrorOccuredInResponseReceivedDelegate = 2278,
        JobMissingOrInInconsistentState = 2279,
        InconsistentStateForResubmissionAttempt = 2280,
        JobConsistencyCheckFailed = 2281,
        JobNotSupporttedBySender = 2282,
        ErrorOccuredInSubmittingDelegate = 2283,
        ErrorWhileObtainingSubmissionTimeoutValue = 2284,
        FailedToStoreThePendingRequestToQueue = 2285,
        FailedToSubmitResponseMessageToQueue = 2286,
        SubmittingMessageToTheSenderTimedOut = 2287
    }
}